=== BKWatch/Package.CodeRage/src/Build/Resource/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  //////////////////////////////////////////////////////////////////////////////
  //
  // Local copy of http://www.w3.org/XML/1998/namespace
  //
  // File:        CodeRage/Build/Resource/project.xsd
  // Date:        Mon, 28 Jan 08 03:31:51 +0000
  // Notice:      This document contains confidential information and
  //              trade secrets
  //
  // Copyright:   2015 CounselNow, LLC
  // Author:      Jonathan Turkanis
  // License:     All rights reserved
  //
  //////////////////////////////////////////////////////////////////////////////
  -->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:pr="http://www.coderage.com/2008/project"
  targetNamespace="http://www.coderage.com/2008/project"
  elementFormDefault="qualified">

  <!-- Shared Simple Types -->

  <simpleType name="identifier">
    <restriction base="string">
      <pattern value="[_a-zA-Z][_a-zA-Z0-9]*"/>
    </restriction>
  </simpleType>

  <simpleType name="compoundIdentifier">
    <restriction base="string">
      <pattern value="[_a-zA-Z][_a-zA-Z0-9]*(\.[_a-zA-Z][_a-zA-Z0-9]*)*"/>
    </restriction>
  </simpleType>

  <simpleType name="framework">
    <annotation>
      <documentation>
        The name of a framework that makes use of pluggable packages modules
      </documentation>
    </annotation>
    <restriction base="pr:identifier"/>
  </simpleType>

  <!-- Attributes -->

  <attributeGroup name="targetAttributes">
    <attribute name="id" type="pr:identifier">
      <annotation>
        <documentation>
          The name of a target, for use on a command line or in a list
          of target dependencies.
        </documentation>
      </annotation>
    </attribute>
    <attribute name="dependsOn">
      <annotation>
        <documentation>
          A list of the names of targets upon which a target depends.
        </documentation>
      </annotation>
      <simpleType>
        <list itemType="pr:identifier"/>
      </simpleType>
    </attribute>
  </attributeGroup>

  <!-- Top-level element -->

  <element name="project">
    <complexType>
      <sequence>
        <element ref="pr:info" minOccurs="0"/>
        <element name="include" minOccurs="0">
          <complexType>
            <attribute name="src" type="anyURI" use="required">
              <annotation>
                <documentation>
                  The pathname of an XML document  conforming to this schema
                  whose root element is 'project' or 'config'.
                </documentation>
              </annotation>
            </attribute>
          </complexType>
        </element>
        <element ref="pr:config" minOccurs="0"/>
        <element ref="pr:tool" minOccurs="0" maxOccurs="unbounded"/>
        <element name="targets" minOccurs="0">
          <complexType>
            <sequence>
              <any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

  <element name="target" abstract="true"/>

  <!-- Project metadata -->

  <element name="info">
    <annotation>
      <documentation>
        Contains project metadata
      </documentation>
    </annotation>
    <complexType>
      <all>
        <element name="label" minOccurs="0">
          <annotation>
            <documentation>
              A descriptive name of the project
            </documentation>
          </annotation>
        </element>
        <element name="description" minOccurs="0">
          <annotation>
            <documentation>
              A detailed description of the project
            </documentation>
          </annotation>
        </element>
        <element name="version" minOccurs="0">
          <annotation>
            <documentation>
              The full version number of the project; any format is acceptable
            </documentation>
          </annotation>
        </element>
        <element name="date" type="dateTime" minOccurs="0">
          <annotation>
            <documentation>
              The project date
            </documentation>
          </annotation>
        </element>
        <element name="copyright" minOccurs="0">
          <annotation>
            <documentation>
              Copyright 2015 CounselNow, LLC
            </documentation>
          </annotation>
        </element>
        <element name="license" minOccurs="0">
          <annotation>
            <documentation>
              License information about the project
            </documentation>
          </annotation>
        </element>
        <element name="author" minOccurs="0">
          <annotation>
            <documentation>
              A semicolon-separated list of author name
            </documentation>
          </annotation>
        </element>
        <element name="link" type="anyURI" minOccurs="0">
          <annotation>
            <documentation>
              The location of additional project information
            </documentation>
          </annotation>
        </element>
      </all>
    </complexType>
  </element>

  <!-- Project configuration -->

  <element name="config" type="pr:configGroup">
    <annotation>
      <documentation>
        Contains project configuration information
      </documentation>
    </annotation>
  </element>

  <complexType name="configGroup">
    <annotation>
      <documentation>
        The type of a "pr:config" element or a "pr:group" descendant of a
        "pr:config" element
      </documentation>
    </annotation>
    <sequence>
      <element name="label" minOccurs="0">
        <annotation>
          <documentation>
            A descriptive name of the property
          </documentation>
        </annotation>
      </element>
      <element name="description" minOccurs="0">
        <annotation>
          <documentation>
            A detailed description of the property
          </documentation>
        </annotation>
      </element>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element name="group" type="pr:configGroup"/>
        <element name="property" type="pr:configProperty"/>
      </choice>
    </sequence>
    <attribute name="name" type="pr:compoundIdentifier" use="optional">
      <annotation>
        <documentation>
          The group's contribution to the names of its descendant properties;
          e.g., if the name of a group is "dataSource.main" and it has a child
          property named "password", the fully qualified property name will
          end with "dataSource.main.password"
        </documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="configProperty">
    <annotation>
      <documentation>
        The type of a "pr:property" descendant of a "pr:config" element
      </documentation>
    </annotation>
    <sequence>
      <element name="label" minOccurs="0">
        <annotation>
          <documentation>
            A descriptive name of the property
          </documentation>
        </annotation>
      </element>
      <element name="description" minOccurs="0">
        <annotation>
          <documentation>
            A detailed description of the property
          </documentation>
        </annotation>
      </element>
    </sequence>
    <attribute name="name" type="pr:compoundIdentifier" use="required">
      <annotation>
        <documentation>
          The property name
        </documentation>
      </annotation>
    </attribute>
    <attribute name="type" use="optional">
      <annotation>
        <documentation>
          The property type
        </documentation>
      </annotation>
      <simpleType>
        <restriction base="string">
          <enumeration value="boolean"/>
          <enumeration value="int"/>
          <enumeration value="float"/>
          <enumeration value="string"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="list" type="boolean" use="optional" default="false">
      <annotation>
        <documentation>
          true if the value of the property is a list of scalar values
        </documentation>
      </annotation>
    </attribute>
    <attribute name="required" type="boolean" use="optional" default="false">
      <annotation>
        <documentation>
          true if a value must be supplied for the property, either in the
          current configuration file or elsewhere
        </documentation>
      </annotation>
    </attribute>
    <attribute name="sticky" type="boolean" use="optional" default="true">
      <annotation>
        <documentation>
          true if the value of the property will be remembered and applied at
          the next build if it is not explicitly set
        </documentation>
      </annotation>
    </attribute>
    <attribute name="obfuscate" type="boolean" use="optional" default="false">
      <annotation>
        <documentation>
          true if the property's value should not be displayed to the user
        </documentation>
      </annotation>
    </attribute>
    <attribute name="value" type="string" use="optional">
      <annotation>
        <documentation>
          The property value
        </documentation>
      </annotation>
    </attribute>
    <attribute name="specifiedAt" type="string" use="optional">
      <annotation>
        <documentation>
          <![CDATA[
          The location of the property specification; used only by
          auto-generated configuration files to record a build configuration;
          consists of a file pathname or one of the strings <command-line> or
          <environment>
          ]]>
        </documentation>
      </annotation>
    </attribute>
    <attribute name="setAt" type="string" use="optional">
      <annotation>
        <documentation>
          <![CDATA[
          The source of the property value; used only by auto-generated
          configuration files to record a build configuration; consists of a
          file pathname or one of the strings <command-line> or
          <environment>
          ]]>
        </documentation>
      </annotation>
    </attribute>
    <attribute name="encoding" use="optional">
      <annotation>
        <documentation>
          Indicates the encoding scheme used to record binary data or lists
          of printable characters when no suitable separator character is
          available
        </documentation>
      </annotation>
      <simpleType>
        <restriction base="string">
          <enumeration value="none"/>
          <enumeration value="base64"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="separator" use="optional">
      <annotation>
        <documentation>
          Separator character used for encoding lists; if not specified,
          strings of internal whitespace characters are interpretted as
          separators
        </documentation>
      </annotation>
      <simpleType>
        <restriction base="string">
          <length value="1"/>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>

  <!-- Packages and channels -->

  <element name="packageGroup" substitutionGroup="pr:target">
    <annotation>
      <documentation>A list of framework packages and channels</documentation>
    </annotation>
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element name="package">
          <complexType>
            <sequence minOccurs="0" maxOccurs="unbounded">
              <element name="property">
                <complexType>
                  <attribute name="name" type="pr:identifier" use="required"/>
                  <attribute name="value" type="string" use="required"/>
                </complexType>
              </element>
            </sequence>
            <attribute name="name" type="string" use="required">
              <annotation>
                <documentation>
                  The package name, in a framework-specific format
                </documentation>
              </annotation>
            </attribute>
            <attribute name="minVersion" type="string">
              <annotation>
                <documentation>
                  The minimum package version, in a framework-specific format
                </documentation>
              </annotation>
            </attribute>
            <attribute name="maxVersion" type="string">
              <annotation>
                <documentation>
                  The maximum package version, in a framework-specific format
                </documentation>
              </annotation>
            </attribute>
            <attribute name="channel" type="anyURI">
              <annotation>
                <documentation>
                  The package channel
                </documentation>
              </annotation>
            </attribute>
          </complexType>
        </element>
        <element name="channel">
          <complexType>
            <attribute name="url" type="anyURI" use="required">
              <annotation>
                <documentation>
                  The channel URL
                </documentation>
              </annotation>
            </attribute>
            <attribute name="username" type="string">
              <annotation>
                <documentation>
                  The username, if any, required for the package manager to
                  access the channel
                </documentation>
              </annotation>
            </attribute>
            <attribute name="password" type="string">
              <annotation>
                <documentation>
                  The username, if any, required for the package manager to
                  access the channel
                </documentation>
              </annotation>
            </attribute>
          </complexType>
        </element>
      </choice>
      <attributeGroup ref="pr:targetAttributes"/>
      <attribute name="framework" type="pr:framework" use="required"/>
      <attribute name="frameworkMinVersion" type="string"/>
      <attribute name="frameworkMaxVersion" type="string"/>
    </complexType>
  </element>

  <!-- Types and elements for automated tests -->

  <element name="test" substitutionGroup="pr:target">
    <annotation>
      <documentation>
        Represents a test suite
      </documentation>
    </annotation>
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="pr:suite"/>
        <element name="include">
          <complexType>
            <attribute name="src" type="anyURI" use="required">
              <annotation>
                <documentation>
                  The pathname of an XML document  conforming to this schema
                  whose root element is 'test'
                </documentation>
              </annotation>
            </attribute>
          </complexType>
        </element>
      </choice>
      <attributeGroup ref="pr:targetAttributes"/>
    </complexType>
  </element>

  <element name="suite">
    <annotation>
      <documentation>
        Represents a test suite or a link to a document defining a test suite.
        If the attribute "command" is present, it must be the sole attribute.
        Otherwise, the attritbute "class" must be present.
      </documentation>
    </annotation>
    <complexType>
      <sequence>
        <element name="param" minOccurs="0" maxOccurs="unbounded">
          <annotation>
            <documentation>
              Represents a constructor parameter
            </documentation>
          </annotation>
          <complexType>
            <attribute name="name" type="pr:identifier" use="required">
              <annotation>
                <documentation>
                  The parameter name
                </documentation>
              </annotation>
            </attribute>
            <attribute name="value" use="required">
              <annotation>
                <documentation>
                  The parameter value
                </documentation>
              </annotation>
            </attribute>
          </complexType>
        </element>
      </sequence>
      <attribute name="classPath" type="anyURI" use="optional">
        <annotation>
          <documentation>
            The location of the test suite's code; may be omitted if the
            suite can be found with autoload
          </documentation>
        </annotation>
      </attribute>
      <attribute name="class" type="string" use="optional">
        <annotation>
          <documentation>
            The name of the class implementing the test suite
          </documentation>
        </annotation>
      </attribute>
      <attribute name="language" type="string" default="php">
        <annotation>
          <documentation>
            The language in which the test suite is implemented
          </documentation>
        </annotation>
      </attribute>
      <attribute name="command" type="string" use="optional">
        <annotation>
          <documentation>
            The command to run
          </documentation>
        </annotation>
      </attribute>
    </complexType>
  </element>

  <!-- Build tools -->

  <element name="tool">
    <annotation>
      <documentation>
        Defines a build tool responsible for handling elements of certain
        types in a project definition file
      </documentation>
    </annotation>
    <complexType>
      <attribute name="class" type="pr:compoundIdentifier" use="required">
        <annotation>
          <documentation>
            The name of a PHP class implementing CodeRage\Build\Tool
          </documentation>
        </annotation>
      </attribute>
      <attribute name="classPath" type="anyURI">
        <annotation>
          <documentation>
            The location of the file defining the PHP class specified by
            the attribyte "class", if it cannot be found by autoloading.
          </documentation>
        </annotation>
      </attribute>
    </complexType>
  </element>

</schema>

=== BKWatch/Package.CodeRage/src/Build/Test/Project/package-pass-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.coderage.com/2008/project"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.coderage.com/2008/project
  ../project.xsd">
  <info>
    <label>Package Pass 4</label>
    <description>
      Installs a package with a channel
    </description>
  </info>
  <targets>
    <testConfiguration status="true" id="ignore">
      <packageConfiguration version="1.0">
        <package name="Foo" version="1.5" channel="http://www.test.com/"/>
        <channel url="http://www.test.com/"/>
      </packageConfiguration>
    </testConfiguration>
    <packageGroup framework="test">
      <package name="Foo" channel="http://www.test.com/"/>
    </packageGroup>
  </targets>
</project>

=== BKWatch/Package.CodeRage/src/Build/Test/Project/package-pass-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.coderage.com/2008/project"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.coderage.com/2008/project
  ../project.xsd">
  <info>
    <label>Package Pass 5</label>
    <description>
      Installs a package with a dependency
    </description>
  </info>
  <targets>
    <testConfiguration status="true" id="ignore">
      <packageConfiguration version="1.0">
        <package name="Foo" version="1.5">
          <dependsOn name="Bar"/>
        </package>
        <package name="Bar" version="3.1"/>
      </packageConfiguration>
    </testConfiguration>
    <packageGroup framework="test">
      <package name="Foo"/>
    </packageGroup>
  </targets>
</project>

=== BKWatch/Package.CodeRage/src/Build/Test/Project/package-pass-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.coderage.com/2008/project"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.coderage.com/2008/project
  ../project.xsd">
  <info>
    <label>Package Pass 2</label>
    <description>
      Installs a package with a maximum version requirement
    </description>
  </info>
  <targets>
    <testConfiguration status="true" id="ignore">
      <packageConfiguration version="1.0">
        <package name="Foo" version="1.5"/>
      </packageConfiguration>
    </testConfiguration>
    <packageGroup framework="test">
      <package name="Foo" maxVersion="2.1"/>
    </packageGroup>
  </targets>
</project>

=== BKWatch/Package.CodeRage/src/Build/Test/Project/target-pass-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.coderage.com/2008/project"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.coderage.com/2008/project
  ../project.xsd">
  <info>
    <label>Target Pass 5</label>
    <description>
      Build a named target
    </description>
  </info>
  <tool class="CodeRage\Build\Test\Tool\Foo"/>
  <targets>
    <testConfiguration status="true" id="ignore" targets="foo"/>
    <foo id="foo" status="success">
      <info>
        <label>First Target</label>
      </info>
    </foo>
  </targets>
</project>
